POST http://localhost:3000/products  HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ODc2ZjMyZWM4NDM1ODk2Y2YzY2M4MiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1MzcwNjMwMCwiZXhwIjoxNzU0MzExMTAwfQ.CvP3zWGV6_mLcvorAv_cgGtsJIns2XA-dqpAeXJGQI8

{
    "title":"Orange",
    "description":"Sweet and tasty",
    "price":"2.40",
    "stockQty":"70",
    "category":"686ba3423ec8f1d1ee190ca1",
    "isSale":"true"
}