GET http://localhost:3000/users  HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NDk1ZTJjODViM2Y1ZWNiMzkyOThiZCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1MDI0NTEyMywiZXhwIjoxNzUwODQ5OTIzfQ.Bd8AnCJtJNYzjIi3AEqxhVN450jBkEF9vd5gcpT1R3g