GET http://localhost:3000/users  HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NDk1ZTJjODViM2Y1ZWNiMzkyOThiZCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc0OTYzODc0NCwiZXhwIjoxNzUwMjQzNTQ0fQ.sgDme33ypwS7yFkMODSbHmABuaT1saLASDnPsfugWi8