PATCH http://localhost:3000/users/6846e3b027e670c5a4725cb8 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NDZlM2IwMjdlNjcwYzVhNDcyNWNiOCIsInJvbGUiOiJjdXN0b21lciIsImlhdCI6MTc0OTQ3NjI5MywiZXhwIjoxNzUwMDgxMDkzfQ.O5Z0Tzu2tAIIPXCwFFgth0kOA4hE0bMedI6NXqO9CYI

{
   "email": "user01@gmail.com"
}