POST http://localhost:3000/users/register  HTTP/1.1
Content-Type: application/json

{
    "login": "adminProduct11",
    "email": "adminProduct11@gmail.com",
    "password": "adminProduct11@gmail.com",
    "role":"admin"
    }